server:
  port: 80

eureka:
  client:
    register-with-eureka: false #自己不能注册
    service-url:
      defaultZone: http://application.yml.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/